# Generated by Django 5.1.8 on 2025-05-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('language', models.CharField(choices=[('en', 'English'), ('zh', 'Chinese'), ('hi', 'Hindi'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic'), ('bn', 'Bengali'), ('ru', 'Russian'), ('pt', 'Portuguese'), ('ur', 'Urdu'), ('id', 'Indonesian'), ('de', 'German'), ('ja', 'Japanese'), ('sw', 'Swahili'), ('mr', 'Marathi'), ('te', 'Telugu'), ('ta', 'Tamil'), ('vi', 'Vietnamese'), ('tr', 'Turkish'), ('ko', 'Korean'), ('fa', 'Persian'), ('it', 'Italian'), ('pl', 'Polish'), ('pa', 'Punjabi'), ('gu', 'Gujarati'), ('ml', 'Malayalam'), ('kn', 'Kannada'), ('my', 'Burmese'), ('th', 'Thai'), ('uk', 'Ukrainian'), ('ro', 'Romanian'), ('nl', 'Dutch'), ('hu', 'Hungarian'), ('cs', 'Czech'), ('el', 'Greek'), ('sv', 'Swedish'), ('fi', 'Finnish'), ('no', 'Norwegian'), ('da', 'Danish'), ('he', 'Hebrew'), ('sr', 'Serbian'), ('hr', 'Croatian'), ('bg', 'Bulgarian'), ('sk', 'Slovak'), ('sl', 'Slovene'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('et', 'Estonian'), ('ka', 'Georgian'), ('hy', 'Armenian'), ('az', 'Azerbaijani'), ('kk', 'Kazakh'), ('uz', 'Uzbek'), ('tk', 'Turkmen'), ('ne', 'Nepali'), ('si', 'Sinhala'), ('lo', 'Lao'), ('km', 'Khmer'), ('mn', 'Mongolian'), ('am', 'Amharic'), ('so', 'Somali'), ('yo', 'Yoruba'), ('ig', 'Igbo'), ('ha', 'Hausa'), ('zu', 'Zulu'), ('xh', 'Xhosa'), ('rw', 'Kinyarwanda'), ('sn', 'Shona'), ('ny', 'Chichewa'), ('tg', 'Tajik'), ('ps', 'Pashto'), ('ky', 'Kyrgyz'), ('qu', 'Quechua'), ('ay', 'Aymara'), ('gn', 'Guarani'), ('ht', 'Haitian Creole'), ('jw', 'Javanese'), ('su', 'Sundanese'), ('ceb', 'Cebuano'), ('ilo', 'Ilocano'), ('mi', 'Maori'), ('sm', 'Samoan'), ('to', 'Tongan'), ('haw', 'Hawaiian'), ('la', 'Latin'), ('eo', 'Esperanto'), ('cy', 'Welsh'), ('gd', 'Scottish Gaelic'), ('ga', 'Irish'), ('br', 'Breton'), ('co', 'Corsican'), ('eu', 'Basque'), ('mt', 'Maltese'), ('bs', 'Bosnian'), ('mk', 'Macedonian'), ('af', 'Afrikaans'), ('is', 'Icelandic'), ('sq', 'Albanian'), ('be', 'Belarusian')], max_length=10)),
            ],
        ),
    ]
