# Generated by Django 5.1.8 on 2025-05-05 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat_groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatgroupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chat_groups.chatgroup'),
        ),
        migrations.AlterUniqueTogether(
            name='chatgroup',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='chatgroupmember',
            unique_together={('group', 'chat_id')},
        ),
    ]
