# Generated by Django 5.1.8 on 2025-05-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchat',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
