# Generated by Django 5.1.8 on 2025-04-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchat',
            name='chat_type',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
