# Generated by Django 5.1.8 on 2025-05-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat_groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('original_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('html', models.BooleanField(default=False)),
                ('schedule_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('button_text', models.CharField(blank=True, help_text='Текст inline-кнопки', max_length=255, null=True)),
                ('button_url', models.URLField(blank=True, help_text='URL inline-кнопки', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='Группы чатов', related_name='scheduled_posts', to='chat_groups.chatgroup')),
            ],
        ),
    ]
