# Generated by Django 5.1.8 on 2025-05-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduled_posts', '0001_initial'),
        ('telegram_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='targets',
            field=models.ManyToManyField(blank=True, help_text='Отдельные чаты/каналы', related_name='scheduled_posts', to='telegram_accounts.telegramchat'),
        ),
    ]
